options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: "cloud-build-sa@emissions-elt-demo.iam.gserviceaccount.com"
steps:
  # Import DAGs to Cloud Composer
  - name: gcr.io/cloud-builders/gsutil
    args:
      - "-m"
      - "rsync"
      - "-d"
      - "-r"
      - "dags"
      - "${_GCS_BUCKET}"

  # Docker Build Schema
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker build -f ./schema/Dockerfile -t us-west4-docker.pkg.dev/${PROJECT_ID}/eed-docker-artifact-repository/deploy-db-migrations --build-arg=PGUSER_ARG=$$PGUSER --build-arg=PGPASSWORD_ARG=$$PGPASSWORD --build-arg=PGHOST_ARG=$$PGHOST .",
      ]
    secretEnv: ["PGUSER", "PGPASSWORD", "PGHOST"]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west4-docker.pkg.dev/${PROJECT_ID}/eed-docker-artifact-repository/deploy-db-migrations",
      ]

  # Entrypoint, timeout and environment variables=
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "jobs",
        "create",
        "--service-account",
        "gke-cloud-compute-sa@emissions-elt-demo.iam.gserviceaccount.com",
        "deploy-db-migrations-${COMMIT_SHA}",
        "--image",
        "us-west4-docker.pkg.dev/${PROJECT_ID}/eed-docker-artifact-repository/deploy-db-migrations",
        "--set-secrets",
        "PGUSER=eed_db_user:latest,PGPASSWORD=eed_db_pass:latest,PGHOST=eed_db_host:latest",
        "--region",
        "us-west4",
        "--execute-now",
      ]

  # Docker Build app
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker build -f ./app/Dockerfile -t us-west4-docker.pkg.dev/${PROJECT_ID}/eed-docker-artifact-repository/app --build-arg NA_SECRET=$$NEXTAUTH_SECRET .",
      ]
    secretEnv: ["PGUSER", "PGPASSWORD", "PGHOST", "NEXTAUTH_SECRET"]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west4-docker.pkg.dev/${PROJECT_ID}/eed-docker-artifact-repository/app",
      ]
    secretEnv: ["NEXTAUTH_SECRET"]

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kubernetes
      - --image=us-west4-docker.pkg.dev/${PROJECT_ID}/eed-docker-artifact-repository/app
      - --location=us-west4-a
      - --cluster=eed-gke
    secretEnv: ["NEXTAUTH_SECRET"]

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/eed_db_user/versions/latest
      env: "PGUSER"
    - versionName: projects/${PROJECT_ID}/secrets/eed_db_pass/versions/latest
      env: "PGPASSWORD"
    - versionName: projects/${PROJECT_ID}/secrets/eed_db_host/versions/latest
      env: "PGHOST"
    - versionName: projects/${PROJECT_ID}/secrets/eed_nextauth_secret/versions/latest
      env: "NEXTAUTH_SECRET"
