options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: "cloud-build-sa@emissions-elt-demo.iam.gserviceaccount.com"
steps:
  # Import DAGs to Cloud Composer
  - name: gcr.io/cloud-builders/gsutil
    args:
      - "-m"
      - "rsync"
      - "-d"
      - "-r"
      - "dags"
      - "${_GCS_BUCKET}"

  # Docker Build Schema
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker build -f ./schema/Dockerfile -t us-west4-docker.pkg.dev/${PROJECT_ID}/eed-docker-artifact-repository/deploy-db-migrations --build-arg=PGUSER_ARG=$$PGUSER --build-arg=PGPASSWORD_ARG=$$PGPASSWORD --build-arg=PGHOST_ARG=$$PGHOST .",
      ]
    secretEnv: ["PGUSER", "PGPASSWORD", "PGHOST"]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west4-docker.pkg.dev/${PROJECT_ID}/eed-docker-artifact-repository/deploy-db-migrations",
      ]

  # Entrypoint, timeout and environment variables=
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "jobs",
        "create",
        "--service-account",
        "gke-cloud-compute-sa@emissions-elt-demo.iam.gserviceaccount.com",
        "deploy-db-migrations-${COMMIT_SHA}",
        "--image",
        "us-west4-docker.pkg.dev/${PROJECT_ID}/eed-docker-artifact-repository/deploy-db-migrations",
        "--set-secrets",
        "PGUSER=eed_db_user:latest,PGPASSWORD=eed_db_pass:latest,PGHOST=eed_db_host:latest",
        "--region",
        "us-west4",
        "--execute-now",
      ]

  # Docker Build app
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker build -f ./app/Dockerfile -t us-west4-docker.pkg.dev/${PROJECT_ID}/eed-docker-artifact-repository/app --build-arg NA_SECRET=$$NEXTAUTH_SECRET --build-arg GOOGLE_CLIENT_ID_ARG=$$GOOGLE_CLIENT_ID --build-arg GOOGLE_CLIENT_SECRET_ARG=$$GOOGLE_CLIENT_SECRET --build-arg GITHUB_ID_ARG=$$GITHUB_ID --build-arg GITHUB_SECRET_ARG=$$GITHUB_SECRET --build-arg NEXTAUTH_URL_ARG=$$NEXTAUTH_URL --build-arg DATABASE_PROTOCOL_ARG=$$DATABASE_PROTOCOL --build-arg DATABASE_USER_ADMIN_ARG=$$DATABASE_USER_ADMIN --build-arg DATABASE_USER_PW_ADMIN_ARG=$$DATABASE_USER_PW_ADMIN --build-arg DATABASE_USER_ANALYST_ARG=$$DATABASE_USER_ANALYST --build-arg DATABASE_USER_PW_ANALYST_ARG=$$DATABASE_USER_PW_ANALYST --build-arg DATABASE_HOST_ARG=$$DATABASE_HOST --build-arg DATABASE_PORT_ARG=$$DATABASE_PORT --build-arg DATABASE_ARG=$$DATABASE --build-arg DATABASE_SCHEMA_ADMIN_ARG=$$DATABASE_SCHEMA_ADMIN --build-arg API_HOST_ARG=$$API_HOST .",
      ]
    secretEnv:
      [
        "PGUSER",
        "PGPASSWORD",
        "PGHOST",
        "NEXTAUTH_SECRET",
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
        "GITHUB_ID",
        "GITHUB_SECRET",
        "NEXTAUTH_URL",
        "DATABASE_PROTOCOL",
        "DATABASE_USER_ADMIN",
        "DATABASE_USER_PW_ADMIN",
        "DATABASE_USER_ANALYST",
        "DATABASE_USER_PW_ANALYST",
        "DATABASE_HOST",
        "DATABASE_PORT",
        "DATABASE",
        "DATABASE_SCHEMA_ADMIN",
        "API_HOST",
      ]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west4-docker.pkg.dev/${PROJECT_ID}/eed-docker-artifact-repository/app",
      ]

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kubernetes
      - --image=us-west4-docker.pkg.dev/${PROJECT_ID}/eed-docker-artifact-repository/app
      - --location=us-west4-a
      - --cluster=eed-gke

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/eed_db_user/versions/latest
      env: "PGUSER"
    - versionName: projects/${PROJECT_ID}/secrets/eed_db_pass/versions/latest
      env: "PGPASSWORD"
    - versionName: projects/${PROJECT_ID}/secrets/eed_db_host/versions/latest
      env: "PGHOST"
    - versionName: projects/${PROJECT_ID}/secrets/eed_nextauth_secret/versions/latest
      env: "NEXTAUTH_SECRET"
    - versionName: projects/${PROJECT_ID}/secrets/eed_nextauth_google_client_id/versions/latest
      env: "GOOGLE_CLIENT_ID"
    - versionName: projects/${PROJECT_ID}/secrets/eed_nextauth_google_client_secret/versions/latest
      env: "GOOGLE_CLIENT_SECRET"
    - versionName: projects/${PROJECT_ID}/secrets/eed_nextauth_github_client_id/versions/latest
      env: "GITHUB_ID"
    - versionName: projects/${PROJECT_ID}/secrets/eed_nextauth_github_client_secret/versions/latest
      env: "GITHUB_SECRET"
    - versionName: projects/${PROJECT_ID}/secrets/eed_nextauth_url/versions/latest
      env: "NEXTAUTH_URL"
    - versionName: projects/${PROJECT_ID}/secrets/eed_database_protocol/versions/latest
      env: "DATABASE_PROTOCOL"
    - versionName: projects/${PROJECT_ID}/secrets/eed_database_user_admin/versions/latest
      env: "DATABASE_USER_ADMIN"
    - versionName: projects/${PROJECT_ID}/secrets/eed_database_user_pw_admin/versions/latest
      env: "DATABASE_USER_PW_ADMIN"
    - versionName: projects/${PROJECT_ID}/secrets/eed_database_user_analyst/versions/latest
      env: "DATABASE_USER_ANALYST"
    - versionName: projects/${PROJECT_ID}/secrets/eed_database_user_pw_analyst/versions/latest
      env: "DATABASE_USER_PW_ANALYST"
    - versionName: projects/${PROJECT_ID}/secrets/eed_database_host/versions/latest
      env: "DATABASE_HOST"
    - versionName: projects/${PROJECT_ID}/secrets/eed_database_port/versions/latest
      env: "DATABASE_PORT"
    - versionName: projects/${PROJECT_ID}/secrets/eed_database/versions/latest
      env: "DATABASE"
    - versionName: projects/${PROJECT_ID}/secrets/eed_database_schema_admin/versions/latest
      env: "DATABASE_SCHEMA_ADMIN"
    - versionName: projects/${PROJECT_ID}/secrets/eed_api_host/versions/latest
      env: "API_HOST"
