  options:
    logging: CLOUD_LOGGING_ONLY
  steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-west1-docker.pkg.dev/${PROJECT_ID}/elt-demo-docker-repo/deploy-db-migrations',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'us-west1-docker.pkg.dev/${PROJECT_ID}/elt-demo-docker-repo/deploy-db-migrations']

  # Entrypoint, timeout and environment variables
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      'beta',
      'run',
      'jobs',
      'create',
      'deploy-db-migrations-${COMMIT_SHA}',
      '--image',
      'us-west1-docker.pkg.dev/${PROJECT_ID}/elt-demo-docker-repo/deploy-db-migrations',
      '--update-secrets',
      'PGUSER=eed_db_user:latest,PGPASSWORD=eed_pg_pass:latest,PGHOST=eed_pg_host:latest',
      '--region',
      'us-west1',
      '--execute-now']
