# This file is for testing the SonarCloud scan. Do not merge.

# Mounting sensitive file system paths is security-sensitive
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - image: k8s.gcr.io/test-webserver
      name: test-container
      volumeMounts:
        - mountPath: /data
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        path: /etc # Sensitive
