apiVersion: apps/v1
kind: Deployment
metadata:
  name: emissions-elt-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eed
  template:
    metadata:
      labels:
        app: eed
    spec:
      containers:
        - name: eed-app
          image: us-west4-docker.pkg.dev/emissions-elt-demo/eed-docker-artifact-repository/app
